notifications:
  email:
    on_success: never
    on_failure: always
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install visualstudio2017-workload-vctools -y
        - choco install python --version=3.8.3
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
        - PowerShell -Command 'cd test'
        - PowerShell -Command 'mkdir target'
        - PowerShell -Command 'Make-msvc.bat'
        - PowerShell -Command 'cd ..'
        - pip install pylint
        - pip install nose
        - pip install coveralls
        - pip install .
script:
  - pylint canaries
  - nosetests
after_success:
  - coveralls
