notifications:
  email:
    on_success: never
    on_failure: always
language: python
python:
  - "3.8"
cache: pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  - pip install pylint
  - pip install coveralls
  - pip install .
script:
  - cd test
  - make all
  - cd ..
  - nosetests
