notifications:
  email:
    on_success: never
    on_failure: always
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install visualstudio2017-workload-vctools -y
        - choco install python --version=3.8.3
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - pip install pylint
        - pip install nose
        - pip install coveralls
        - pip install .
script:
  - cd test
  - mkdir target
  - Make-msvc.bat
  - cd ..
  - pylint canaries
  - nosetests
after_success:
  - coveralls
